### ISSUE TITLE
Static file delivery does not work on windows

### ISSUE THREAD

**Issue by Trolldemorted** [ENOFLAG/ENOKEY#25]
`fn static_files(file: PathBuf)` and `fn key_files(file: PathBuf)` take a PathBuf, and on windows PathBufs contain backslashes.

**Comment by fsck** [comment]
Is this a bug in our implementation or an upstream issue? Have you found any upstream references for this issue?

**Comment by Trolldemorted** [comment]
That depends on what you consider a bug, I suppose. The PathBuf is working as it should, the question is whether a PathBuf is a reasonable choice here.
