### ISSUE TITLE
Fix potential DirTrav

### ISSUE THREAD

**Issue by domenukk** [ENOFLAG/ENOKEY#32]
This code looks suspicious.
I don't see any documented safety feature preventing /keyfile/../../../../etc/passwd in the docs.
https://github.com/ENOFLAG/ENOKEY/blob/7425cc88ad181b49e691edcb10b2688817de3d11/src/main.rs#L216

**Comment by Trolldemorted** [comment]
Do we need a whitelist at all? Serving static files can be done easier:
```rust
extern crate rocket;
extern crate rocket_contrib;

#[cfg(test)] mod tests;

use rocket_contrib::serve::StaticFiles;

fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", StaticFiles::from("static"))
}

fn main() {
    rocket().launch();
}
```

Since this would also solve #25, I recommend we move the templates out of /static (they shouldn't be there in the first place) and let rocket handle serving everything in /static.

cc @fsck
