### ISSUE TITLE
Add HTTP Security Headers

### ISSUE THREAD

**Issue by domenukk** [ENOFLAG/ENOKEY#33]
Some basic security considerations should be made, such as csps with "no inline javascript", x-frame-options: SAMEORIGIN and others. 
For more infos, see
https://www.keycdn.com/blog/http-security-headers
https://pentest-tools.com/blog/essential-http-security-headers/

**Comment by Trolldemorted** [comment]
Do we want more headers or can we close this?

**Comment by domenukk** [comment]
There are probably 20 more I don't know about but we can close this issue :)
