### ISSUE TITLE
docker and docker-compose support

### ISSUE THREAD

**Issue by Trolldemorted** [ENOFLAG/ENOKEY#4]

**Comment by fsck** [comment]
This should be closed by #24.

**Comment by Trolldemorted** [comment]
an experimental dockerfile without any means to actually deploy a file and literally no documentation is not docker support! :)

**Comment by bitwave** [comment]
A docker-compose file is missing, too.

**Comment by parafoxx** [comment]
can we close this? we have a dockerfile in the repo and a docker compose example in the readme

**Comment by Trolldemorted** [comment]
This repo does not link to our images, there is no hint that we do have images on dockerhub at all, and the sample does not pull the official builds but tries to build `.` instead.

**Comment by fsck** [comment]
These issues should be fixed when we merge #50, right?
